title: Smart Barpak
email: smartbarpak@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Smart Barpak is the Gorkha's 1st Smart Village.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://barpak.org
asset_url: /assets

google_analytics: G-2ZEY98LGJJ

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - README.md
